### PR TITLE
add list-hostnames handler/queue endpoint

### PR DESCRIPTION
**Pull request by ddellacosta**
This along with [this PR](https://github.com/democracyworks/turbovote-admin-http-api/pull/34) will allow admins to edit partner campus addresses, which is currently not working.

Troy, if you are satisfied with this PR please go ahead and push it live while I'm gone.

### CODE REVIEW

**Comment by tank157** [comment]
@ddellacosta There was already an endpoint to handle this: https://github.com/democracyworks/partner-works/blob/master/src/partner_works/handlers/campus_address.clj#L92

**Comment by cap10morgan** [comment]
Do we need this? Wouldn't using the existing `list` handler with a `(map :domain)` on the other end do the same thing?

**Comment by tank157** [comment]
@cap10morgan That probably would work too. It's probably overkill now to send all the partner-site info just to power a drop-down, but some day we may allow some editing of partner-site values from an admin screen.

**Comment by cap10morgan** [comment]
I guess I'm kind of thinking about the inverse. It seems like overkill to add a whole new handler for a subset of the data that was already available from an existing one (unless we're running into a performance or security issue or similar).

**Comment by tank157** [comment]
Also a valid position as well. I think the other PR also needs some work anyway, but maybe I can just close this one down, rework `turbovote-admin-http-api` to use the existing endpoint and pull domain out of it, while also fixing the filter problems that I think are likely to occur.

**Comment by ddellacosta** [comment]
Sounds like Magda wants to wait on pushing these in any case so may be worth just leaving them as is until I'm back.

@cap10morgan I could go either way--I started by thinking about just using the existing endpoint but felt like it was a pretty small amount of work to just add a new, trivial endpoint, especially since it was so much more efficient to directly get hostnames from the db vs. all the fiddling we do now. I guess it's performance (arguably not worth worrying about for these endpoints anyways) vs. maintenance load and I could go either way.

**Comment by ddellacosta** [comment]
I should add, these two PRs are only really here because I was concerned that Magda et all would want administrative access to manage campus addresses while I'm gone. If that's not an issue for then I'd definitely advocate waiting, 'cause it sounds like there's enough ambiguity here that it's worth taking a step back here and thinking harder on how to do these.

**Comment by ddellacosta** [comment]
@cap10morgan @tank157 
Closing this one for now since it sounds like we'd rather avoid the overhead of a new endpoint vs. use one that may not be perfectly optimal but does the job.

**Pull request closed without merging**
